services:
  reactfrontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nodebackend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file: ./server/.env